### ISSUE TITLE
Running out of memory in 'somaticsniper:convert_BAM2Pileup_SAMtools (2)'

### ISSUE THREAD

**Issue by Alfredo-Enrique** [uclahs-cds/pipeline-call-sSNV#255]
**Describe the bug**
Not necessarily a bug, more of a request for input on what the next actionable items are when running to such an out of memory issue ( besides just using an M64. which might take days to open up)

* Pipeline release version : 7.0.0-rc.2
* Cluster you are using : Slurm
* Node type : F72
* Submission method : Metapipeline-DNA
* Actual submission script :  /hot/user/alfgonzalez/project/project-LAND-SARC/project-SARC-LAND/pipeline/SGSALASC/metapipeline-DNA/run_script/launch_metapipeline-DNA-5.x.x_SGSALASC_paired_recalibrate-bam_entry_SGSALASC000017.sh
* Config files: /hot/user/alfgonzalez/project/project-LAND-SARC/project-SARC-LAND/pipeline/SGSALASC/metapipeline-DNA/config/WGS_SGSALASC_meta.input.config
* Path to the working directory : Don't have this because of metapipeline but below is the log that was produced.
* Any logs produced by the pipeline
- log: /hot/project/disease/SarcomaTumor/SARC-000118-SarcomaLandscape/data/SGSALASC/WGS/metapipeline-DNA-5.2.0/workdir/1b/1733fd479db71b8aa1e6fc7242c16b/.command.log
- general-directory: /hot/project/disease/SarcomaTumor/SARC-000118-SarcomaLandscape/data/SGSALASC/WGS/metapipeline-DNA-5.2.0/workdir/1b/1733fd479db71b8aa1e6fc7242c16b/

**To Reproduce**
1. You can use this launch script, make sure to change the log path location
2. Make sure the config is launching the call-sSNV pipeline only
3. And change the ouput folder location for the files in the config
4. Should take ~10 hours

**Expected behavior**
Run out of memory error. I tried manually increasing the alloted memory for convert_BAM2Pileup_SAMtools all the way to 136GB. However it still fails. Per the F72 config, there is a retry option which has been enabled that retrys the process subsequently adding 5GB of memory until failure.

**Screenshots**

Error:
<img width="581" alt="Screenshot 2023-12-09 at 4 14 46 PM" src="https://github.com/uclahs-cds/pipeline-call-sSNV/assets/60890801/3d47c1b8-083b-4d9e-8ea0-c4486367be3d">

Here are the modified resource allocation parameters I tried last:

<img width="1984" alt="Screenshot 2023-12-09 at 4 13 09 PM" src="https://github.com/uclahs-cds/pipeline-call-sSNV/assets/60890801/31fcc0a4-29f6-4426-b580-4b802f97c390">

**Additional context**
There's an M64 job that has been going for 8+ days. I may just launch it once that is finished to see if that fixes it and get an idea of the higher end of memory needed.

**Comment by sorelfitzgibbon** [comment]
Has anything changed with the reference sequence?  It looks like it might be failing while trying to index the reference (`somaticsniper` uses a very old version of `samtools` for this).  But if this is the same reference as always (which it seems to be), then that doesn't make sense.  I will run a test of just `somaticsniper` directly in `pipeline-call-sSNV` with your input files.   
```
  Command error:
    [fai_load] build FASTA index.
    .command.sh: line 3:    28 Killed                  samtools pileup -vcf Homo_sapiens_assembly38.fasta BWA-MEM2-2.2.1_GATK-4.2.4.1_SARC-000118-SarcomaLandscape_SGSALASC000017-T007-O03-F.bam > SomaticSniper-1.0.5.0_SARC-000118-SarcomaLandscape_SGSALASC000017-T007-O03-F_raw-tumor.pileup
```

Also, it looks like the `samtools pileup` process will use a provided index file, and we should be passing that in regardless, so I'll test that too.

**Comment by Alfredo-Enrique** [comment]
Updates: So I been trying different parameters over the last couple of days and I got one to work! Although I don't really know why? Maybe there's a flag/issue brought up by the old samtools version but unsure.

Context:

I first pulled up the docker image for somatic sniper which has the old samtools version and tried to do the command mannually in an F16 with 8GB of memory. Since it's one of the first processes, there isn't anything that precedes or affects the file. However this command, which is modeled exactly after the pipeline process fails even when done mannually in an F16.

```
 set -euo pipefail samtools pileup -vcf  /hot/ref/reference/GRCh38-BI-20160721/Homo_sapiens_assembly38.fasta  Homo_sapiens_assembly38.fasta BWA-MEM2-2.2.1_GATK-4.2.4.1_SARC-000118-SarcomaLandscape_SGSALASC000017-T007-O03-F.bam > SomaticSniper-1.0.5.0_SARC-000118-SarcomaLandscape_SGSALASC000017-T007-O03-F_raw-tumor.pileup
```

Second, again in the F16 + docker image, after playing around with it I realized that removing the ' set -euo pipefail' the command worked and properly gave the expected output when perfomred manually :

```
samtools pileup -vcf  /hot/ref/reference/GRCh38-BI-20160721/Homo_sapiens_assembly38.fasta  Homo_sapiens_assembly38.fasta BWA-MEM2-2.2.1_GATK-4.2.4.1_SARC-000118-SarcomaLandscape_SGSALASC000017-T007-O03-F.bam > SomaticSniper-1.0.5.0_SARC-000118-SarcomaLandscape_SGSALASC000017-T007-O03-F_raw-tumor.pileup
```

Third: I tried it in the pipeline. The two modifications I did were 1. remove the 'set -euo pipefail' from this specific process, and 2. Manually increased the memory allocation for the convert_BAM2Pileup_SAMtools process in the F72.config to 132 GB. This worked and provided an output of the pipeline. 

```
/hot/project/disease/SarcomaTumor/SARC-000118-SarcomaLandscape/data/SGSALASC/WGS/metapipeline-DNA-5.2.0/SARC-000118-SarcomaLandscape/main_workflow/output/call-sSNV-7.0.0-rc.2/SGSALASC000017-T007-O03-F
``` 

Now, I don't now if it is 1. (removal of 'set -euo pipefail') or 2. The manual change of the resource allocation in the config proper that allowed it to work.  With regards to the resource, previously I had tried to modify the resource, but that was directly from the config level as per the first post. If the manual change of the memory is what helped it go proceed, it could be that the memory specifications from the metapipeline config are not being passed onto the call-sSNV pipeline. However, the call-sSNV pipeline does have a retry strategy that adds 5GB of memory each time, but unsure now many times it retries until it fails.

**Comment by yashpatel6** [comment]
Quick note here, it very likely should not be related to the `set -euo pipefail`; that only sets up how errors in the bash script are handled and what constitutes an error

**Comment by sorelfitzgibbon** [comment]
Some notes on testing this (to be continued)
 - Specifying on the command line  (`-r chr9` or `-l regions.bed`) to use chr1 or chr9 only - all fail with memory errors (32GB available)
 - Giving an input bam with only chr9, same header - succeeded
 
I haven’t tested enough to know if this is sporadic.  I would like to figure it out to see if we can avoid future problems.  It might come down to the VERY old version of samtools in somaticsniper being triggered by something in the modern samples.  Note, the process usually uses less than 1GB.
