### ISSUE TITLE
Update repository description to match standard

### ISSUE THREAD

**Issue by nwiltsie** [uclahs-cds/pipeline-call-sSNV#283]
Per the most recent [Nextflow Working Group](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/268369922/2024-04-10+Nextflow+Working+Group+Meeting+Notes) meeting, each pipeline's repository description should:

* Begin with "Nextflow pipeline to "
* Exactly match the description in `metadata.yaml`

Repository: `A Nextflow pipeline to identify the somatic single nucleotide variants (sSNVs) by comparing a pair of tumor/normal samples.`
Metadata: `A Nextflow pipeline to identify the somatic single nucleotide variants (sSNVs) by comparing a pair of tumor/normal samples.`

**Comment by sorelfitzgibbon** [comment]
Fixed with [d5bc47bf](https://github.com/uclahs-cds/pipeline-call-sSNV/commit/d5bc47bf0d1cccbfae7e01a142342cec93267175)
