### ISSUE TITLE
running without a `panel of normals` now elicits a WARNING

### ISSUE THREAD

**Issue by sorelfitzgibbon** [uclahs-cds/pipeline-call-sSNV#308]
>WARN: Access to undefined parameter `panel_of_normals_vcf` -- Initialise it to a default value eg. `params.panel_of_normals_vcf = some_value

**Comment by yashpatel6** [comment]
https://github.com/uclahs-cds/pipeline-call-sSNV/blob/4d5dd5a460073dcb5d9336c154263ec95c4b3c21/module/mutect2-processes.nf#L95

Needs to be updated to
```
panel_of_normals =  params.getOrDefault("panel_of_normals_vcf", null) ? "--panel-of-normals ${params.panel_of_normals_vcf}" : ""
```
